apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: vaccination
type: Opaque
data:
  # base64 encoded: echo -n "pass" | base64
  POSTGRES_PASSWORD: cGFzcw==  # "pass"
  # для production использовать настоящие секреты!